git:
  depth: 10
  
branches:
  only:
  - master
  
language: ruby

rvm:
- 2.4

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GIT_NAME="Dylan M. Taylor"
  - GIT_EMAIL="dylan@dylanmtaylor.com"
  - secure: IRsUK9FwoLyg09pQdwAXPqN8DFdMCiV7abZKCIyye445braGDX2m4679w0bMtto281ic4534S5yOvpNXBR4b/1muhjj1v+1U27VHH33XEufChgZGEB1PCXszYfLzW5UQww32gb4hXmorOV6VaxZrOS20d9BSM7iXyEA2XtUy49UWQaiEEDBy5wjRQNXot+saumV7velHYWldIYPwlybRLkXC6Gmpwzxi4SgxHlJU3Snz4/92yCgmMRh01/7AIcq9OX9W6dMT2vVdIUynvG4u7WevkMoF7RE36vwQ4tjeQSPBzy1rB23bEHAH2/X3j1XdCT4oEa898C5WKceIf+tcrOz1V3Ta/ROX/8txbHUUS16QpmR9DNwSQoZmaYLGRNUAEgH8jZh0UU9bFRNc+6esZRrpJIstlJbpOIMLZeehWFt5C08lvFFBjdjee2DRVOZ1mGFwD5hEwbqD3utX38DyJbzZ5PTGS04yoGTMySW7Qmw554SprrbNOs9/mkRJeitckn6iwl8AaFNKMJpdelTmFBkCuYWrFOWoJ7Rs0j/rdXsFQo8MdH6oGQ86f92YHi2yLVYgOuthkL58zhZOVdYpPJda7tvYpb+R9bp6Vmh/Ahvl7A4QfAJUYVEAezt3iUdTJu1c+fgf6QKVSA4k6F0+phHzQV+NtE+m3wVgwNb8xVA=
  matrix:
  - NODE_VERSION=0.12

os:
- linux

sudo: false

install:
- gem install jekyll

before_script:
- python build_site.py
- cp -v interface/* blog/_includes/
- cd ./blog/

script: jekyll build

after_script:
- cd ..
- echo $GIT_NAME
- echo $GIT_EMAIL
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- export REPO="https://"$GITHUB_TOKEN"@github.com/dylanmtaylor/dylanmtaylor.github.io.git"
- export REPO_NAME="dylanmtaylor.github.io"
- export TARGET_DIR=$(mktemp -d /tmp/$REPO_NAME.XXXX)
- export REV=$(git rev-parse HEAD)
- git clone --branch master ${REPO} ${TARGET_DIR}
- rsync -rvt --del --exclude=".git" /home/travis/build/dylanmtaylor/dylanmtaylor.github.io/ $TARGET_DIR
- cd $TARGET_DIR
- git add -A .
- git commit -m "Built from commit $REV"
- git push origin master

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - ruby
    - ruby-dev
