git:
  depth: 10

branches:
  only:
  - master

language: ruby

rvm:
- 2.4

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GIT_NAME="Dylan M. Taylor"
  - GIT_EMAIL="dylan@dylanmtaylor.com"
  matrix:
  - NODE_VERSION=0.12

os:
- linux

sudo: false

install:
- gem install jekyll jekyll-feed jekyll-sass-converter liquid colorator kramdown mercenary rouge safe_yaml github-pages

before_script:
- python build_site.py
- cp -v interface/* blog/_includes/
- cd ./blog/

script: jekyll build

after_script:
- cd ..
- echo $GIT_NAME
- echo $GIT_EMAIL
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- export REPO="https://"$GIT_TOKEN"@github.com/dylanmtaylor/dylanmtaylor.github.io.git"
- export REPO_NAME="dylanmtaylor.github.io"
- export TARGET_DIR=$(mktemp -d /tmp/$REPO_NAME.XXXX)
- export REV=$(git rev-parse HEAD)
- git clone --branch master ${REPO} ${TARGET_DIR}
- rsync -rvt --del --exclude=".git" /home/travis/build/dylanmtaylor/dylanmtaylor.github.io/ $TARGET_DIR
- cd $TARGET_DIR
- if [ "$(git status | grep 'modified:' | grep -v feed.xml | wc -l)" -gt "0" ]; then git add -A .; fi # Fix for feed updating forever bug
- git commit -m "Built from commit $REV"
- git push origin master

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - ruby
    - ruby-dev
