git:
  depth: 10

language: ruby
rvm:
- 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

  matrix:
    - NODE_VERSION=0.12

os:
  - linux

sudo: false

install:
  - gem install jekyll

before_script:
  - python build_site.py
  - cp interface/* blog/_includes/
  - cd ./blog/

script: jekyll build

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - gems
    - ruby
    - ruby-dev
