url: http://dylanmtaylor.com
baseurl: "/pages/blog" # the subpath of your site, e.g. /blog/
#markdown: rdiscount
permalink: pretty
highlighter: true
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']
destination: ../pages/blog/
